// Generated by scripts/generate-state-machine.mjs. Do not edit.
export const stateMachine = [
  {
    "event": "submit",
    "source": "draft",
    "target": "submitted",
    "actor_types": [
      "human"
    ],
    "roles": [
      "reporter"
    ],
    "requires_reason": false,
    "note": ""
  },
  {
    "event": "start_clarification",
    "source": "submitted",
    "target": "clarifying",
    "actor_types": [
      "ai",
      "system"
    ],
    "roles": [],
    "requires_reason": false,
    "note": ""
  },
  {
    "event": "draft_without_clarification",
    "source": "submitted",
    "target": "ai_drafted",
    "actor_types": [
      "ai",
      "system"
    ],
    "roles": [],
    "requires_reason": false,
    "note": ""
  },
  {
    "event": "clarification_complete",
    "source": "clarifying",
    "target": "ai_drafted",
    "actor_types": [
      "ai",
      "system"
    ],
    "roles": [],
    "requires_reason": false,
    "note": ""
  },
  {
    "event": "queue_for_review",
    "source": "ai_drafted",
    "target": "under_review",
    "actor_types": [
      "system"
    ],
    "roles": [],
    "requires_reason": false,
    "note": ""
  },
  {
    "event": "reject",
    "source": "under_review",
    "target": "rejected",
    "actor_types": [
      "human"
    ],
    "roles": [
      "reviewer"
    ],
    "requires_reason": true,
    "note": ""
  },
  {
    "event": "request_info",
    "source": "under_review",
    "target": "info_requested",
    "actor_types": [
      "human"
    ],
    "roles": [
      "reviewer"
    ],
    "requires_reason": true,
    "note": ""
  },
  {
    "event": "provide_info",
    "source": "info_requested",
    "target": "clarifying",
    "actor_types": [
      "human"
    ],
    "roles": [
      "reporter"
    ],
    "requires_reason": false,
    "note": ""
  },
  {
    "event": "escalate",
    "source": "under_review",
    "target": "escalated",
    "actor_types": [
      "human"
    ],
    "roles": [
      "reviewer"
    ],
    "requires_reason": true,
    "note": ""
  },
  {
    "event": "approve_action",
    "source": "under_review",
    "target": "action_assigned",
    "actor_types": [
      "human"
    ],
    "roles": [
      "reviewer"
    ],
    "requires_reason": false,
    "note": ""
  },
  {
    "event": "approve_after_escalation",
    "source": "escalated",
    "target": "action_assigned",
    "actor_types": [
      "human"
    ],
    "roles": [
      "reviewer"
    ],
    "requires_reason": false,
    "note": ""
  },
  {
    "event": "reject_after_escalation",
    "source": "escalated",
    "target": "rejected",
    "actor_types": [
      "human"
    ],
    "roles": [
      "reviewer"
    ],
    "requires_reason": true,
    "note": ""
  },
  {
    "event": "submit_evidence",
    "source": "action_assigned",
    "target": "action_submitted",
    "actor_types": [
      "human"
    ],
    "roles": [
      "responsible"
    ],
    "requires_reason": false,
    "note": ""
  },
  {
    "event": "verification_failed",
    "source": "action_submitted",
    "target": "action_assigned",
    "actor_types": [
      "human"
    ],
    "roles": [
      "reviewer"
    ],
    "requires_reason": true,
    "note": ""
  },
  {
    "event": "verify_and_close",
    "source": "action_submitted",
    "target": "verified_closed",
    "actor_types": [
      "human"
    ],
    "roles": [
      "reviewer"
    ],
    "requires_reason": false,
    "note": ""
  },
  {
    "event": "draft_lesson",
    "source": "verified_closed",
    "target": "lesson_drafted",
    "actor_types": [
      "ai",
      "system"
    ],
    "roles": [],
    "requires_reason": false,
    "note": ""
  },
  {
    "event": "publish_lesson",
    "source": "lesson_drafted",
    "target": "lesson_published",
    "actor_types": [
      "human"
    ],
    "roles": [
      "reviewer"
    ],
    "requires_reason": false,
    "note": ""
  }
] as const;
export type StateMachineTransition = (typeof stateMachine)[number];
export const reportStatuses = ["action_assigned","action_submitted","ai_drafted","clarifying","draft","escalated","info_requested","lesson_drafted","lesson_published","rejected","submitted","under_review","verified_closed"] as const;
export type ReportStatus = (typeof reportStatuses)[number];
export const reportStatus = {
  "action_assigned": "action_assigned",
  "action_submitted": "action_submitted",
  "ai_drafted": "ai_drafted",
  "clarifying": "clarifying",
  "draft": "draft",
  "escalated": "escalated",
  "info_requested": "info_requested",
  "lesson_drafted": "lesson_drafted",
  "lesson_published": "lesson_published",
  "rejected": "rejected",
  "submitted": "submitted",
  "under_review": "under_review",
  "verified_closed": "verified_closed"
} as const;
export const statusColourMap: Record<ReportStatus, readonly [string, string]> = {
  "action_assigned": [
    "success-tint",
    "success-strong"
  ],
  "action_submitted": [
    "success-tint",
    "success-strong"
  ],
  "ai_drafted": [
    "primary-tint",
    "primary-strong"
  ],
  "clarifying": [
    "primary-tint",
    "primary-strong"
  ],
  "draft": [
    "surface-sunken",
    "ink-muted"
  ],
  "escalated": [
    "danger-tint",
    "danger"
  ],
  "info_requested": [
    "warning-tint",
    "warning"
  ],
  "lesson_drafted": [
    "surface-sunken",
    "ink-muted"
  ],
  "lesson_published": [
    "success-tint",
    "success-strong"
  ],
  "rejected": [
    "surface-sunken",
    "ink-muted"
  ],
  "submitted": [
    "primary-tint",
    "primary-strong"
  ],
  "under_review": [
    "warning-tint",
    "warning"
  ],
  "verified_closed": [
    "success-tint",
    "success-strong"
  ]
};
