// Generated by scripts/generate-state-machine.mjs. Do not edit.
export const stateMachine = [] as const;
export type StateMachineTransition = (typeof stateMachine)[number];
export const reportStatuses = [] as const;
export type ReportStatus = (typeof reportStatuses)[number];
export const statusColourMap = {} as const;
