// Generated by scripts/generate-state-machine.mjs. Do not edit.
export const stateMachine = [] as const;
export type StateMachineTransition = (typeof stateMachine)[number];
export const reportStatuses = ["action_assigned","action_submitted","ai_drafted","clarifying","draft","escalated","info_requested","lesson_drafted","lesson_published","rejected","submitted","under_review","verified_closed"] as const;
export type ReportStatus = (typeof reportStatuses)[number];
export const statusColourMap: Record<ReportStatus, readonly [string, string]> = {
  "action_assigned": [
    "success",
    "successStrong"
  ],
  "action_submitted": [
    "success",
    "successStrong"
  ],
  "ai_drafted": [
    "primaryTint",
    "primaryStrong"
  ],
  "clarifying": [
    "primaryTint",
    "primaryStrong"
  ],
  "draft": [
    "surfaceSunken",
    "inkMuted"
  ],
  "escalated": [
    "danger",
    "danger"
  ],
  "info_requested": [
    "warning",
    "warning"
  ],
  "lesson_drafted": [
    "surfaceSunken",
    "inkMuted"
  ],
  "lesson_published": [
    "success",
    "successStrong"
  ],
  "rejected": [
    "surfaceSunken",
    "inkMuted"
  ],
  "submitted": [
    "primaryTint",
    "primaryStrong"
  ],
  "under_review": [
    "warning",
    "warning"
  ],
  "verified_closed": [
    "success",
    "successStrong"
  ]
};
